/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package scaffolds

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"sigs.k8s.io/kubebuilder/v4/pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart_templates/manager"

	"sigs.k8s.io/yaml"

	log "github.com/sirupsen/logrus"
	"sigs.k8s.io/kubebuilder/v4/pkg/config"
	"sigs.k8s.io/kubebuilder/v4/pkg/machinery"
	"sigs.k8s.io/kubebuilder/v4/pkg/plugins"
	"sigs.k8s.io/kubebuilder/v4/pkg/plugins/optional/helm"
	"sigs.k8s.io/kubebuilder/v4/pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates"
	"sigs.k8s.io/kubebuilder/v4/pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart_templates"
	templatescertmanager "sigs.k8s.io/kubebuilder/v4/pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart_templates/certmanager"
	templateswebhooks "sigs.k8s.io/kubebuilder/v4/pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart_templates/webhook"
)

var _ plugins.Scaffolder = &initScaffolder{}

type initScaffolder struct {
	config config.Config

	// fs is the filesystem that will be used by the scaffolder
	fs machinery.Filesystem

	// force indicates whether to scaffold controller files even if they exist
	force bool
}

// NewInitHelmScaffolder returns a new Scaffolder for HelmPlugin
func NewInitHelmScaffolder(config config.Config, force bool) plugins.Scaffolder {
	return &initScaffolder{
		config: config,
		force:  force,
	}
}

// InjectFS implements cmdutil.Scaffolder
func (s *initScaffolder) InjectFS(fs machinery.Filesystem) {
	s.fs = fs
}

// Scaffold scaffolds the Helm chart with the necessary files.
func (s *initScaffolder) Scaffold() error {
	log.Println("Generating Helm Chart to distribute project")

	// Initialize the map to store the extracted images from deploy-image plugin
	deployImages := make(map[string]string)

	// Detect and extract the deploy-image plugin configuration
	pluginConfig := struct {
		Resources []struct {
			Kind    string            `json:"kind"`
			Options map[string]string `json:"options"`
		} `json:"resources"`
	}{}

	err := s.config.DecodePluginConfig("deploy-image.go.kubebuilder.io/v1-alpha", &pluginConfig)
	if err == nil {
		// Extract images for the resources
		for _, res := range pluginConfig.Resources {
			image, ok := res.Options["image"]
			if ok {
				deployImages[strings.ToUpper(res.Kind)] = image
			}
		}
	}

	// Extract webhooks from generated YAML files (generated by controller-gen)
	webhooks, err := extractWebhooksFromGeneratedFiles()
	if err != nil {
		return fmt.Errorf("failed to extract webhooks: %w", err)
	}

	// Initialize the machinery.Scaffold that will write the files to disk
	scaffold := machinery.NewScaffold(s.fs,
		machinery.WithConfig(s.config),
	)

	// Pass the extracted images and webhooks to the HelmValues template
	buildScaffold := []machinery.Builder{
		&templates.HelmChart{},
		&templates.HelmValues{
			Webhooks:     webhooks,
			DeployImages: deployImages,
			Force:        s.force,
		},
		&templates.HelmIgnore{},
		&chart_templates.HelmHelpers{},
		&manager.ManagerDeployment{
			Force:        s.force,
			DeployImages: len(deployImages) > 0,
			HasWebhooks:  len(webhooks) > 0,
		},
		&templatescertmanager.Certificate{},
	}

	if len(webhooks) > 0 {
		buildScaffold = append(buildScaffold, &templateswebhooks.WebhookTemplate{})
		buildScaffold = append(buildScaffold, &templateswebhooks.WebhookService{})
	}

	if err := scaffold.Execute(buildScaffold...); err != nil {
		return fmt.Errorf("error scaffolding helm-chart manifests: %v", err)
	}

	// Copy relevant files from config/ to dist/chart/templates/
	err = copyConfigFiles(s.config.GetProjectName())
	if err != nil {
		return err
	}

	return nil
}

// Extract webhooks from manifests.yaml file
func extractWebhooksFromGeneratedFiles() ([]helm.WebhookYAML, error) {
	var webhooks []helm.WebhookYAML
	manifestFile := "config/webhook/manifests.yaml"
	if _, err := os.Stat(manifestFile); err == nil {
		content, err := os.ReadFile(manifestFile)
		if err != nil {
			return nil, fmt.Errorf("failed to read manifests.yaml: %w", err)
		}

		// Process the content to extract webhooks
		webhooks = append(webhooks, extractWebhookYAML(content)...)
	} else {
		// Return empty if no webhooks were found
		return webhooks, nil
	}

	return webhooks, nil
}

// extractWebhookYAML parses the webhook YAML content and returns a list of WebhookYAML
func extractWebhookYAML(content []byte) []helm.WebhookYAML {
	var webhooks []helm.WebhookYAML

	type WebhookConfig struct {
		Kind     string `yaml:"kind"`
		Webhooks []struct {
			Name         string `yaml:"name"`
			ClientConfig struct {
				Service struct {
					Name      string `yaml:"name"`
					Namespace string `yaml:"namespace"`
					Path      string `yaml:"path"`
				} `yaml:"service"`
				CABundle string `yaml:"caBundle"`
			} `yaml:"clientConfig"`
			Rules                   []helm.WebhookRule `yaml:"rules"`
			FailurePolicy           string             `yaml:"failurePolicy"`
			SideEffects             string             `yaml:"sideEffects"`
			AdmissionReviewVersions []string           `yaml:"admissionReviewVersions"`
		} `yaml:"webhooks"`
	}

	// Split the input into different documents (to handle multiple YAML docs in one file)
	docs := strings.Split(string(content), "---")

	for _, doc := range docs {
		var webhookConfig WebhookConfig
		if err := yaml.Unmarshal([]byte(doc), &webhookConfig); err != nil {
			log.Errorf("Error unmarshalling webhook YAML: %v", err)
			continue
		}

		// Determine the webhook type (mutating or validating)
		webhookType := "unknown"
		if webhookConfig.Kind == "MutatingWebhookConfiguration" {
			webhookType = "mutating"
		} else if webhookConfig.Kind == "ValidatingWebhookConfiguration" {
			webhookType = "validating"
		}

		// Parse each webhook and append it to the result
		for _, webhook := range webhookConfig.Webhooks {
			for i := range webhook.Rules {
				// If apiGroups is empty, set it to [""] to ensure proper YAML output
				if len(webhook.Rules[i].APIGroups) == 0 {
					webhook.Rules[i].APIGroups = []string{""}
				}
			}
			webhooks = append(webhooks, helm.WebhookYAML{
				Name:                    webhook.Name,
				Type:                    webhookType,
				Path:                    webhook.ClientConfig.Service.Path,
				Rules:                   webhook.Rules,
				FailurePolicy:           webhook.FailurePolicy,
				SideEffects:             webhook.SideEffects,
				AdmissionReviewVersions: webhook.AdmissionReviewVersions,
			})
		}
	}
	return webhooks
}

// Helper function to copy files from config/ to dist/chart/templates/
func copyConfigFiles(projectName string) error {
	configDirs := []struct {
		SrcDir  string
		DestDir string
		SubDir  string
	}{
		{"config/rbac", "dist/chart/templates/rbac", "rbac"},
		{"config/crd/bases", "dist/chart/templates/crds", "crd"},
		{"config/prometheus", "dist/chart/templates/prometheus", "prometheus"},
		{"config/network-policy", "dist/chart/templates/network-policy", "networkPolicy"},
	}

	for _, dir := range configDirs {
		files, err := filepath.Glob(filepath.Join(dir.SrcDir, "*.yaml"))
		if err != nil {
			return err
		}

		for _, srcFile := range files {
			destFile := filepath.Join(dir.DestDir, filepath.Base(srcFile))
			err := copyFileWithHelmLogic(srcFile, destFile, dir.SubDir, projectName)
			if err != nil {
				return err
			}
		}
	}

	return nil
}

// copyFileWithHelmLogic reads the source file, modifies the content for Helm, and writes it to the destination
func copyFileWithHelmLogic(srcFile, destFile, subDir, projectName string) error {
	if _, err := os.Stat(srcFile); os.IsNotExist(err) {
		log.Printf("Source file does not exist: %s", srcFile)
		return err
	}

	content, err := os.ReadFile(srcFile)
	if err != nil {
		log.Printf("Error reading source file: %s", srcFile)
		return err
	}

	contentStr := string(content)

	// Skip kustomization.yaml or kustomizeconfig.yaml files
	if strings.HasSuffix(srcFile, "kustomization.yaml") || strings.HasSuffix(srcFile, "kustomizeconfig.yaml") {
		log.Printf("Skipping irrelevant file: %s", srcFile)
		return nil
	}

	// Apply the replacement for ServiceAccount in RBAC files
	if subDir == "rbac" {
		contentStr = strings.Replace(contentStr,
			"name: controller-manager",
			fmt.Sprintf("name: %s-controller-manager", projectName), -1)
	}

	// Apply the replacement for the metrics monitor name in Prometheus files
	if subDir == "prometheus" {
		contentStr = strings.Replace(contentStr,
			"name: controller-manager-metrics-monitor",
			fmt.Sprintf("name: %s-controller-manager-metrics-monitor", projectName), 1)
	}

	// Remove existing labels if necessary
	contentStr = removeLabels(contentStr)

	// Replace namespace with Helm template variable
	contentStr = strings.ReplaceAll(contentStr, "namespace: system", "namespace: {{ .Release.Namespace }}")

	// Add Helm labels logic
	contentStr = strings.Replace(contentStr, "metadata:", `metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}`, 1)

	// Wrap the content with Helm conditional logic based on the subdirectory (e.g., "rbac", "manager")
	wrappedContent := fmt.Sprintf("{{- if .Values.%s.create }}\n%s{{- end -}}\n", subDir, contentStr)

	// Create the destination directory if needed
	if err := os.MkdirAll(filepath.Dir(destFile), os.ModePerm); err != nil {
		return err
	}

	// Write the modified content to the destination file
	err = os.WriteFile(destFile, []byte(wrappedContent), os.ModePerm)
	if err != nil {
		log.Printf("Error writing destination file: %s", destFile)
		return err
	}

	log.Printf("Successfully copied %s to %s", srcFile, destFile)
	return nil
}

// removeLabels removes any existing labels section from the content
func removeLabels(content string) string {
	labelRegex := `(?m)^  labels:\n(?:    [^\n]+\n)*`
	re := regexp.MustCompile(labelRegex)

	return re.ReplaceAllString(content, "")
}
