name: release
on:
  pull_request:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.19'
      - name: Get the image tag
        if: startsWith(github.ref, 'refs/tags')
        run: |
          # Source: https://github.community/t/how-to-get-just-the-tag-name/16241/32
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo IMAGE_TAG="${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      - name: Create a draft release
        uses: actions/create-release@v1
        id: release
        if: startsWith(github.ref, 'refs/tags')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: 0.177.0
          args: release -f ./build/.goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: kubebuilder
          path: dist/*
          if-no-files-found: error



