name: run-test-e2e-for-project-v4-sample

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'

      - name: Run initial tests and setup envtest
        run: |
          cd testdata/project-v4
          go mod tidy
          make test

      - name: Check etcd status without network
        run: |
          if pgrep -x "./testdata/project-v4/bin/k8s/1.30.0-darwin-arm64/etcd" > /dev/null
          then
            echo "etcd is running"
          else
            echo "etcd is NOT running"
          fi

      - name: Check Kubernetes API Server status without network
        run: |
          if pgrep -x "./testdata/project-v4/bin/k8s/1.30.0-darwin-arm64/kube-apiserver" > /dev/null
          then
            echo "Kubernetes API Server is running"
          else
            echo "Kubernetes API Server is NOT running"
          fi    

      - name: Check kubectl status without network
        run: |
          if command -v ./testdata/project-v4/bin/k8s/1.30.0-darwin-arm64/kubectl > /dev/null
          then
            echo "kubectl is installed"
          else
            echo "kubectl is NOT installed"
          fi

      - name: Simulate network issues
        run: sudo tc qdisc add dev lo root netem loss 100%

      - name: Check etcd status without network
        run: |
          if pgrep -x "./testdata/project-v4/bin/k8s/1.30.0-darwin-arm64/etcd" > /dev/null
          then
            echo "etcd is running"
          else
            echo "etcd is NOT running"
          fi

      - name: Check Kubernetes API Server status without network
        run: |
          if pgrep -x "./testdata/project-v4/bin/k8s/1.30.0-darwin-arm64/kube-apiserver" > /dev/null
          then
            echo "Kubernetes API Server is running"
          else
            echo "Kubernetes API Server is NOT running"
          fi    

      - name: Check kubectl status without network
        run: |
          if command -v ./testdata/project-v4/bin/k8s/1.30.0-darwin-arm64/kubectl > /dev/null
          then
            echo "kubectl is installed"
          else
            echo "kubectl is NOT installed"
          fi

      - name: Run make test without network connection
        run: |
          cd testdata/project-v4
          make test

      - name: Remove network simulation
        run: sudo tc qdisc del dev lo root netem
